[package]
name = "dash_rust"
version = "0.1.0"
authors = ["Evan Ritscher <evan.ritscher@gmail.com>"]
edition = "2018"

[dependencies]
pnet = "0.22.0"
lazy_static = "1.3.0"
clap = "2.32.0"
serde_json = "1.0.39"
